version: '3'
services:
  apex:
    build: .
    ports:
      - "8080:8080"
    environment:
      - RUST_LOG=apex=info,actix_web=info,diesel=info
      - DATABASE_URL=postgres://defaultuser:defaultpassword@db/apex
      - KAFKA_ADDRESS=kafka:9092
      - KAFKA_USERNAME=
      - KAFKA_PASSWORD=
      - KAFKA_GROUP_ID=
      - KAFKA_TOPIC=test
      - SERVER_ADDRESS=0.0.0.0:8080
  kafka:
    image: "bitnami/kafka:latest"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper
    volumes:
      - ./persist/kafka:/bitnami/kafka
  db:
    image: "postgres"
    volumes:
      - ./persist/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=defaultpassword
      - POSTGRES_USER=defaultuser
      - POSTGRES_DB=apex
  zookeeper:
    image: "bitnami/zookeeper:latest"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
